[build]
  publish = "dist"
  command = "npm run build:web"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start-web"
  port = 8081

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"